using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Api.Migrations
{
    public partial class autoGeneratedFullName : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Information_FullName",
                table: "Users",
                type: "text",
                nullable: false,
                computedColumnSql: "\"Users\".\"Information_GivenName\" || ' ' || \"Users\".\"Information_Surname\"",
                stored: true,
                oldClrType: typeof(string),
                oldType: "text");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Information_FullName",
                table: "Users",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text",
                oldComputedColumnSql: "\"Users\".\"Information_GivenName\" || ' ' || \"Users\".\"Information_Surname\"");
        }
    }
}
